openapi: 3.0.3
info:
  title: Simple Newslertter
  description: Service to convert RSS and Atom feeds to newsletters|
  contact:
    url: https://simple-newsletter.com/
  version: 1.1.0
externalDocs:
  url: https://simple-newsletter.com/
servers:
  - url: https://simple-newsletter.com/v1
tags:
  - name: subscriptions
paths:
  /subscriptions/:
    get:
      tags:
        - subscriptions
      description: Starts subscription process
      operationId: subscriptionRequest
      parameters:
        - name: uri
          in: query
          description: Feed\'s URI to subscribe
          schema:
            type: string
            format: uri
          required: true
          example: https://example.org/feed.atom
        - name: email
          in: query
          description: E-mail to receive articles from subscribed feed
          schema:
            type: string
            format: email
          required: true
          example: email@example.org
        - name: return
          in: query
          description: URI to return (with a 302 Redirect) the user after subscription
          schema:
            type: string
            format: uri
          required: false
      responses:
        '200':
          description: Subscription requested successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONResponse'
            text/html:
              schema:
                type: string
        '302':
          description: |
            Subscription response redirected
            When parameter *return* is provided the response will be a 302 redirect to the specified URI with aditional query parameters indicating the result of the operation.

            Additional query parameters:
              - title
              - result
              - ok
        '400':
          description: Subscription request failed due to invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONResponse'
            text/html:
              schema:
                type: string
        'default':
          description: Internal server error
components:
  schemas:
    JSONResponse:
      type: object
      properties:
        title:
          type: string
        detail:
          type: string
