openapi: 3.0.3
info:
  title: Simple Newslertter
  description: Service to convert RSS and Atom feeds to newsletters
  contact:
    url: https://simple-newsletter.com/
  version: 1.0.0
externalDocs:
  url: https://simple-newsletter.com/
servers:
  - url: https://simple-newsletter.com/v1
tags:
  - name: subscriptions
paths:
  /subscriptions/:
    get:
      tags:
        - subscriptions
      description: Starts subscription process
      operationId: subscriptionRequest
      parameters:
        - name: uri
          in: query
          schema:
            type: string
            format: uri
          required: true
        - name: email
          in: query
          schema:
            type: string
            format: email
          required: true
      responses:
        '200':
          description: Subscription requested successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONResponse'
            text/html:
              schema:
                type: string
        '400':
          description: Subscription request failed due to invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONResponse'
            text/html:
              schema:
                type: string
        '500':
          description: Internal server error
components:
  schemas:
    JSONResponse:
      type: object
      properties:
        title:
          type: string
        detail:
          type: string
